import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@styles/globals.css"

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // middleware();

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
